/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package collecto;
import collecto.controller.Board;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Board board = new Board();
        board.testBoard();
    }
}
